### ISSUE TITLE
Implicit cast compilation error is misleading.

### ISSUE THREAD

**Issue by Nimeshius** [Practical/practical-sa#2]
When compiling the following code:
{
   def var1: s32 = 5;
   def var2: u32 = var1;
   //Do something.
}

I get a compilation error along the lines of:
"s32 cast to u32 is not allowed"

This error is misleading as an **explicit** cast is allowed, it is just not allowed implicitly.

**Comment by Shachar** [comment]
Thank you for the report. The issue is now fixed in master.
